### ISSUE TITLE
Force all recommended VSCode extensions to be activated automatically

### ISSUE THREAD

**Issue by thomasfrobieter** [webksde/ddev-vscode-devcontainer-drupal9-template#28]
Some recommended extensions are requested to be activated automatically by vscode while first starting 'ddev code' (PHP Debug & Apache Conf in my test).

while others not:

![recommended_vscode_extensions_ddev](https://user-images.githubusercontent.com/4060313/136186447-81647f4d-f437-4ecd-911a-6f1dec49d1fb.png)

There is no difference between these extensions in the config file, so it's probably a vscode bug? https://github.com/webksde/ddev-vscode-devcontainer-drupal9-template/blob/main/.ddev/initiation-additions/.vscode/extensions.json.

===
Update:
Tried again with a clean install (ddev delete, deleted docker containers and images, removed repo).
Installed it again, started VSCode with 'ddev code', the extensions which were installed in the previous test are still installed, no request to install recommended extensions on first startup.

**Comment by joshsedl** [comment]
Trying to resovle this problem will take some time unfortunatly Since VS-Code will attach to our web container we only have extensions saved locally on our machine, for windows:  "C:\Users\Joshua Sedler\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\imageConfigs\drud%2fddev-webserver%3av1.18.0-ddev-vscode-devcontainer-drupal9-template-built.json"
We can also create a named config file with the command "Remote-Containers: Open Named Configuration File" this will create another named config file, but almost in the same directory.

Because we are attaching the VSCode-Container and don't build a VS-Code Container from the ground up, we don't have a "devcontainer.json". Usually in a "devcontainer.json" we define the docker-compose files, set the forwarded ports and the SETTINGS and EXTENSIONS. Since we want to use our ddev web containers php-instance we ATTACH VS-Code rather than creating a separate PHP instance defined in a Docker Compose file which we will then link in a .devcontainer.json for a STANDALONE VSCode-Container.

**Comment by joshsedl** [comment]
Using "code --install-extension <extension-id>" will unfortunately only install the extension locally and NOT in our attached VSCode. Running "code --install-extension <extension-id>" in "ddev ssh" will throw an error, since it doesn't know "code". Running "code --install-extension <extension-id>" in the VSCode bash also throws an error! Curiously, it knows "code" in the VSCode bash, which doesn't make sense, since we are in the same  web container as with ddev ssh

**Comment by joshsedl** [comment]
This is a major issue though, since we currently don't set the settings in the container settings, but we create a workspace in our projects file structure and set the settings in the workspace. Extensions will only show as recommendations once, like @thomasfrobieter already mentioned and if you initialize a ddev environment after completely whipping it from docker aka a clean install (ddev delete, deleted docker containers and images, removed repo).
VSCode will still save your settings and extensions in the before mentioned local extensions.yml

**Comment by joshsedl** [comment]
Closing this and link it in https://github.com/webksde/ddev-vscode-devcontainer-drupal9-template/issues/74
